/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "firstName": "Test FirstName",
           *       "lastName": "Test LastName",
           *       "email": "user@example.com",
           *       "password": "P@ssw0rd",
           *       "passwordRepeat": "P@ssw0rd"
           *     }
           */
          "application/json": components["schemas"]["RegisterRequestDto"];
          /**
           * @example {
           *       "firstName": "Test FirstName",
           *       "lastName": "Test LastName",
           *       "email": "user@example.com",
           *       "password": "P@ssw0rd",
           *       "passwordRepeat": "P@ssw0rd"
           *     }
           */
          "text/json": components["schemas"]["RegisterRequestDto"];
          /**
           * @example {
           *       "firstName": "Test FirstName",
           *       "lastName": "Test LastName",
           *       "email": "user@example.com",
           *       "password": "P@ssw0rd",
           *       "passwordRepeat": "P@ssw0rd"
           *     }
           */
          "application/*+json": components["schemas"]["RegisterRequestDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["AuthResponseDto"];
            "application/json": components["schemas"]["AuthResponseDto"];
            "text/json": components["schemas"]["AuthResponseDto"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          /**
           * @example {
           *       "email": "user@example.com",
           *       "password": "P@ssw0rd"
           *     }
           */
          "application/json": components["schemas"]["LoginRequestDto"];
          /**
           * @example {
           *       "email": "user@example.com",
           *       "password": "P@ssw0rd"
           *     }
           */
          "text/json": components["schemas"]["LoginRequestDto"];
          /**
           * @example {
           *       "email": "user@example.com",
           *       "password": "P@ssw0rd"
           *     }
           */
          "application/*+json": components["schemas"]["LoginRequestDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["AuthResponseDto"];
            "application/json": components["schemas"]["AuthResponseDto"];
            "text/json": components["schemas"]["AuthResponseDto"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["RefreshRequestDto"];
          "text/json": components["schemas"]["RefreshRequestDto"];
          "application/*+json": components["schemas"]["RefreshRequestDto"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["AuthResponseDto"];
            "application/json": components["schemas"]["AuthResponseDto"];
            "text/json": components["schemas"]["AuthResponseDto"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthResponseDto: {
      accessToken?: string | null;
      /** Format: int32 */
      expiresInSeconds?: number;
      refreshToken?: string | null;
      tokenType?: string | null;
      user?: components["schemas"]["UserResponseDto"];
    };
    LoginRequestDto: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    RefreshRequestDto: {
      refreshToken: string;
    };
    RegisterRequestDto: {
      firstName: string;
      lastName: string;
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
      /** Format: password */
      passwordRepeat: string;
    };
    UserResponseDto: {
      /** Format: uuid */
      id?: string;
      firstName?: string | null;
      lastName?: string | null;
      email?: string | null;
      role?: string | null;
      /** Format: int64 */
      createdAtUnix?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
